// Builds the static playground under site/. Three steps, no server-side anything:
//   1. site/presets/*.ts  ->  site/src/presets.generated.ts (each preset's own source, as a
//      string, so the editor shows exactly the file the CLI can render and lint)
//   2. tsc --noEmit over site/ (presets included — a broken example fails the build here,
//      not in a user's browser)
//   3. esbuild x2: the library as a standalone ES module the page loads at runtime, and the
//      playground app itself
// The library bundle stays separate from the app bundle on purpose: user code typed into the
// editor imports that same URL, so the editor's `sketch` is the instance the app mounts.
import * as esbuild from "esbuild";
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const siteDir = path.join(root, "site");
const vendorDir = path.join(siteDir, "vendor");

// Every current browser the page claims to support, and nothing older — the renderer needs
// SVG masks and Web Animations-era APIs regardless, so downlevelling further buys nothing.
const BROWSER_TARGETS = ["chrome100", "firefox100", "safari15"];

function buildPresets() {
  const presetsDir = path.join(siteDir, "presets");
  const files = readdirSync(presetsDir)
    .filter((name) => name.endsWith(".ts"))
    .sort();
  if (files.length === 0) throw new Error("no presets found in site/presets");

  const presets = files.map((file) => {
    const source = readFileSync(path.join(presetsDir, file), "utf-8");
    const firstLine = source.split("\n", 1)[0];
    if (!firstLine.startsWith("//")) {
      throw new Error(`${file}: the first line must be a "// Label" comment — it becomes the picker label`);
    }
    return {
      // Numeric prefixes order the picker; they aren't part of the id a share link or a
      // bug report would quote.
      id: file.replace(/\.ts$/, "").replace(/^\d+-/, ""),
      label: firstLine.replace(/^\/\/\s*/, "").trim(),
      source,
    };
  });

  const generated = `// Generated by scripts/build-site.mjs from site/presets/*.ts — do not edit.
export interface Preset {
  id: string;
  label: string;
  source: string;
}

export const presets: Preset[] = ${JSON.stringify(presets, null, 2)};
`;
  writeFileSync(path.join(siteDir, "src/presets.generated.ts"), generated, "utf-8");
  return presets;
}

function typecheck() {
  execFileSync(process.execPath, [path.join(root, "node_modules/typescript/bin/tsc"), "-p", path.join(siteDir, "tsconfig.json")], {
    stdio: "inherit",
  });
}

async function bundle() {
  mkdirSync(vendorDir, { recursive: true });
  const shared = {
    bundle: true,
    format: "esm",
    platform: "browser",
    target: BROWSER_TARGETS,
    minify: true,
    // sucrase reads it; without a value esbuild leaves a reference to a global that does
    // not exist in a browser.
    define: { "process.env.NODE_ENV": '"production"' },
  };

  await esbuild.build({
    ...shared,
    entryPoints: [path.join(siteDir, "src/lib-entry.ts")],
    outfile: path.join(vendorDir, "sketchling.mjs"),
  });

  await esbuild.build({
    ...shared,
    entryPoints: [path.join(siteDir, "src/main.ts")],
    outfile: path.join(vendorDir, "playground.js"),
  });
}

const presets = buildPresets();
typecheck();
await bundle();

const sizes = ["sketchling.mjs", "playground.js"]
  .map((name) => `${name} ${(statSync(path.join(vendorDir, name)).size / 1024).toFixed(0)}kB`)
  .join(", ");
console.log(`Built site/ — ${presets.length} presets, ${sizes}`);
